### ISSUE TITLE
Touch Input Checklist

### ISSUE THREAD

**Issue by NyakoFox** [TerryCavanagh/VVVVVV#1197]
- [ ] Menus converted to a mobile-friendly format (#1164)
- [ ] Level menu redesign (WIP by @NyakoFox)
- [ ] Gameplay control styles
  - [ ] D-pad (#1160)
  - [ ] Swipe (#1172)
  - [ ] Sides
- [ ] The touch control tutorial (#1201)
- [x] Saving when you touch a checkpoint (#1174)
- [ ] Level editor controls
