### ISSUE TITLE
2.3 TODO

### ISSUE THREAD

**Issue by flibitijibibo** [TerryCavanagh/VVVVVV#267]
This is a quick tracker for things we're going to check out before 2.3 is tagged. We're on ~month 6 of the VVVVVV source release and we've gotten a ton of contributions (and horrifying bug discoveries), so I think this is a good time to start thinking about pushing an official update.

Current Schedule: July 1 will be a feature freeze, and ~July 14 31~ ~October 1 31~ January 10 will be the release. No features will be merged after July 1, only bug fixes will be accepted until 2.3 is out.

I'll add a milestone tag for issues already filed, but the broader things we need to do featurewise:

- [x] Merge the 60fps patchset
- [x] Close or Acknowledge bugs tagged as 2.3 items
- [x] Update the CONTRIBUTORS file, GitHub Friends list
- [x] GitHub Superfriends list

Not much, but the 60fps patchset in particular needs as much playtesting as possible this month. Other than that, @InfoTeddy's got some things from CE to upstream, I'll let them maintain a list here as well.

**Comment by InfoTeddy** [comment]
Things from VCE:
- [ ] Proper support for Gray Warp Zone tileset in custom levels
- [ ] Support for putting levels and assets in a single zip file
- [ ] Playtesting ghosts (think Super Mario Maker)
- [ ] Shift+F1/F2/F3 editor hotkeys
- [ ] 7x7 and 9x9 tools, horizontal/vertical tools

**Comment by AllyTally** [comment]
> Playtesting ghosts (think Super Mario Maker)

[Here's what ghosts look like currently in VCE.](https://o.lol-sa.me/6exrtnS.mp4) When I was writing this originally, I didn't upstream it because I felt like it didn't make too much sense in vanilla--though I do see why it'd be accepted, as long as there's an option to disable it. Does anyone have a stance on this?

**Comment by TerryCavanagh** [comment]
Oh, that's cool! Yeah, that would be a nice inclusion for v2.3, if it can be disabled in the options.

**Comment by AllyTally** [comment]
I've opened a pull request for editor ghosts. #279

**Comment by Fussmatte** [comment]
Will anything from 2.3 be implemented into console releases, e.g. Nintendo Switch, PS4 etc?

**Comment by InfoTeddy** [comment]
Well, the console versions are made by Nicalis, so you'd have to ask them. No one has control of the console versions other than them.

**Comment by flibitijibibo** [comment]
Last call for new features - the freeze is in effect after I tag FNA 20.07, usually an hour or two before noon Eastern time.

**Comment by flibitijibibo** [comment]
We're now in feature freeze - no new features will be accepted until 2.3 is out. At this point, all attention should be put on performance fixes and regressions from 2.2.

**Comment by flibitijibibo** [comment]
Delaying the tag date from July 14 to July 31 - I was given a pretty lengthy list of bugs that we should probably fix and then re-test, particularly for some of the new features that got added (and 60fps mode). Those bugs are being filed now, so we can have all the issues in a single place.

**Comment by flibitijibibo** [comment]
Doing a pretty substantial bump of the tag date again... to October 1.

I sorta got blindsided by the number of bugs and regressions that came up, so it looks like we need more time to cover everything. At the same time, I'm going to be somewhat occupied with another project for the back half of July and then _very_ occupied with the FNA3D launch for pretty much all of August. FNA3D releases on September 1, so I'll probably be putting out fires there for a couple weeks after that... which pretty much leaves me with 2 actual weeks to freely look at VVV myself, between now and October (unless SoR4 QA starts right at that point, argh).

Hopefully this will be enough time to give each bug the attention they need...  yes, this feature freeze is going to be _long_, but there are lots of issues filed, so there's plenty of stuff to be done anyway. Focus should still be put entirely on fixes rather than features.

**Comment by flibitijibibo** [comment]
It's been a while!

We actually came surprisingly close to meeting this, but FNA3D has kept me a bit more occupied than expected (also Streets of Rage 4 _finally_ started moving recently) so we'll just push it back to Halloween this time. We're down to only 7 issues that don't directly require me or Terry, so it's finally starting to wrap up!

**Comment by flibitijibibo** [comment]
Surprise surprise, we've got another delay... I'll have to say "screw it" again and push this to January 10. A few reasons just from me: They Bleed Pixels Switch launch, followed by Streets of Rage 4 launch, followed by Superliminal launch, followed by moving to a new place, with Quadrilateral Cowboy 64-bit, Star-Twine, and an undisclosed port assessment sprinkled in between. That's all before the end of November!

The bug list is really really small though, so provided that gets focused on first I might be able to move the launch closer to December, but not enough attention has been put there lately (a lot of InfoTeddy's work has been on getting existing TASes to sync again, which is arguably more important than everything else).

**Comment by Dav999-v** [comment]
Just my opinion, but if you think about it, most of the remaining issues are pretty minor, yet hard and boring for anyone to look into. They boil down to this:
- #369 Temporary graphical glitch in the background if you go to the options menu while running up the Tower
- #377 Nice-to-have
- #390 Incorrect music in a minigame upon specific input
- #401 Requires frame-perfect input or keymashing to get an interface glitch
- Also, #387, alledgedly this can't easily be fixed, and it just seems like a minor annoyance for the player that they can avoid or solve pretty easily

I'd argue that 2.2, which is still the most recent version, has a lot more severe bugs. For me the only issue that would be really worth delaying the release for is #373/#487, because not having that means any time you want to check something in 2.2 or accidentally open it, you've probably reset a good part of your settings. I don't really mind the other issues :slightly_smiling_face:

**Comment by flibitijibibo** [comment]
Even so, I'm not in a position to manage a release - I typically monitor releases _very_ closely for post-launch support, and my schedule doesn't have much room for that until at least December.

**Comment by TerryCavanagh** [comment]
That works for me - I'm still head down working on Dicey Dungeons switch stuff and don't really have the time I'd like to properly test 2.3 anyway!

**Comment by flibitijibibo** [comment]
Quick update since I have a few hours left before the month _really_ starts: We're now on the final 3 (!!!) unassigned bugs, so I'll outline what's left real quick:

Assigned:

- #373 is currently being handled by Misa
- #387 and #18 are my bugs, I'll deal with these but they're not critical for final QA

Unassigned:

- #377 is the highest priority of the unassigned issues. This is something that usually isn't a big deal on PC but would fail cert just about anywhere else. Since we're now making lots of changes to the engine we'll need to be a lot safer than we were before.
- #401 is middle priority; it's hard to do but it is _possible_, and we've done a lot of menu work already so we may as well stamp this one out.
- #390 is the lowest priority, bordering on getting demoted to 2.4. I'm inclined to demote it if this also happened with 2.2, but we did do a fair amount of work to the music engine so it may be worth trying to fix this anyway. If this isn't a regression and all the other issues (including the ones assigned to me) get fixed except for this, I'll demote it to 2.4.

**Comment by InfoTeddy** [comment]
> #390 is the lowest priority, bordering on getting demoted to 2.4. I'm inclined to demote it if this also happened with 2.2, but we did do a fair amount of work to the music engine so it may be worth trying to fix this anyway. If this isn't a regression and all the other issues (including the ones assigned to me) get fixed except for this, I'll demote it to 2.4.

Just tested 2.2 just now, it does not happen in 2.2. So it's a regression.

**Comment by flibitijibibo** [comment]
#377 is all that's left now - I've made a freeze exception to let @InfoTeddy try and fix the game loop order again, so the last issue is still up for grabs. Once that's done we'll be ready for round 1 of QA; round 2 will be for the loop order and then we'll do one last check for my windowing fixes before tagging.

**Comment by anna328p** [comment]
Potentially create a Project board for releases?

**Comment by flibitijibibo** [comment]
Quick update since we're in mid-December... the board looks roughly the same, but we do have patches for most of it:

https://github.com/TerryCavanagh/VVVVVV/issues?q=is%3Aissue+is%3Aopen+label%3A%22required+for+2.3%22

My office is up and running now but the move did not go smoothly at all - I'll still take responsibility for #387 and I'll keep reviewing things, but we may end up cutting it close and tagging 2.3-RC1 rather than 2.3 in January instead.

**Comment by AllyTally** [comment]
Just a quick question, what's the current status on 2.3? Nothing happened in January, and there's been no talk about it since... are there any plans?

**Comment by flibitijibibo** [comment]
At this point it's really just "when all the labeled issues are resolved," I'm still assigned to #387 but the rest are available.

**Comment by flibitijibibo** [comment]
Just merged the very last blocker into master. We have a couple things we want to merge in still, but my plan is to post 2.3-RC1 to Steam at some point this week. For those keeping a close eye on the 2.3 label:

- #387 was deemed either machine-specific or specific to Windows 10. Win10 is a regression festival pretty much year round, so I'm not sure how much I care about this one.
- #377 is _basically_ done, it just doesn't include the XML hardening which is a huge undertaking, and this update's taken long enough already... so we'll file a separate issue under 2.4 later.
- #18 I'll do in the final package. Not much to see here, just an icon update.
- All the pull requests marked for 2.3 are minor style/design choices, so those are getting done whenever Terry can take a look.

Lastly, not on the tracker, is me making a GitHub Superfriends page so I can throw Misa in there. This may come as a surprise, but Misa has basically written 95% of the commits from 2.2 to 2.3, so I _think_ this is warranted...

Thanks to everyone for their patience! 14 months for what's effectively a top-to-bottom rewrite isn't so bad, right?

**Comment by leo60228** [comment]
> Win10 is a regression festival pretty much year round, so I'm not sure how much I care about this one.

My understanding is that #387 is a regression from 2.2, so it'd be strange for it to be a bug in Windows 10.

**Comment by flibitijibibo** [comment]
If someone wants to try and fix it they're welcome to, but my experience with Win10 is that any fix you apply bitrots anyway. As far as I can tell the current window management works on every display system _except_ Windows 10, and not on every PC running it. The current plan is to ship as-is, so if anyone _really_ cares about this your time is now very limited.

**Comment by AllyTally** [comment]
I would like to mention that with my current testing, the bug seems to be gone...
I do still believe this was an SDL bug, as it only happened on a specific version of SDL. It didn't exist on an older version of SDL, it did exist for quite a while on a newer version, and now that I've updated SDL versions again (since some of the recent commits require it) it's gone again.
Of course, there isn't much evidence for this other than my observations, however I think the issue can be ignored for now until it pops up again.

**Comment by flibitijibibo** [comment]
The first release candidate is now on Steam under the "2.3-testing" branch. It's pretty much straight out of the Git repo, with the TODO items still not in place yet.

**Comment by TerryCavanagh** [comment]
I've just announced the testing branch on twitter! https://twitter.com/terrycavanagh/status/1380703571818110977

It's been a long time since the last update, so I reckon let's give it at least two weeks before we set it live. Nice work, everyone <3 (and to you in particular, @InfoTeddy!)

**Comment by flibitijibibo** [comment]
The patches/reports have slowed down from what I can tell, so we're down to the final few items which are mostly isolated patches: #681, #682, #749, and #758. Once these have been reviewed I'll do one last rebuild, and if nothing shows up that will be what gets tagged as 2.3!

**Comment by TerryCavanagh** [comment]
Heya! I reviewed those patch, merged three and have put a pin in the other one until v2.4. I think we're ready!

**Comment by TerryCavanagh** [comment]
Had a look, sorry, I think no (in it's current implementation)

**Comment by flibitijibibo** [comment]
New build is live on 2.3-testing. Provided nothing bad happens we're just looking at #764. Tentatively I'm looking at June 1 for the final tag, but that doesn't factor in any release prep we have to do before making it the default version.

**Comment by flibitijibibo** [comment]
As you might expect at this point, we'll need to wait a little longer while #764 and #770 are figured out.

**Comment by flibitijibibo** [comment]
New Steam beta is up, fixes the last of the regressions reported up to this point.

To make life easier and to buy us some time on any _more_ regressions, I'm just going to make the call that VVVVVV 2.3 will be tagged at the same time as SDL 2.0.16. I expect this to happen really soon since we want the Wayland updates out _really_ soon (ideally before NVIDIA drops the Linux 470.xx atomic bomb).

**Comment by flibitijibibo** [comment]
New 2.0.16 release date is August 7th! Will do a rebuild of VVV tomorrow morning, that will be the last test build before release if nothing comes up.

**Comment by flibitijibibo** [comment]
Steam beta has been updated with the latest - I expect no changes at this point except for #790, so last call for regressions!

**Comment by InfoTeddy** [comment]
I'm hard at work working on a VVVVVV video right now, which will be finished either tomorrow or the day after that; when that's done I'll send in a few things.

**Comment by flibitijibibo** [comment]
SDL 2.0.16 is now available - the beta has been updated accordingly. Provided #799 and #811 go well I expect this to be tagged between August 17 and August 24 (pending a final review and official release date from Terry).

**Comment by flibitijibibo** [comment]
One more build is up - I believe Misa's pushed all that's left, so if nothing changes for 7 days in a row the tag will be August 31. (Gives me a little more bit time to squeeze in a Wayland update that I want to do really soon.)

**Comment by InfoTeddy** [comment]
By the way, if anyone wants to view a changelog for this huge update... [here you go](https://vsix.dev/wiki/Version_2.3).

**Comment by AllyTally** [comment]
Please note with the above changelog, there were many PRs I skipped while writing the initial list, so there's definitely some things missing, however everything important is there.

**Comment by flibitijibibo** [comment]
Tag's going up in about an hour, so we're done here...
