### ISSUE TITLE
Terry's Localisation To-Do List

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/VVVVVV#863]
Just a personal checklist of things for me to do on the Localisation project:

 - [x] Fill in the room name context in the localisation branch (in https://github.com/Dav999-v/VVVVVV/blob/localization/desktop_version/lang/en/roomnames.xml and https://github.com/Dav999-v/VVVVVV/blob/localization/desktop_version/lang/en/roomnames_special.xml)
 - [x] Check with Bennett about any I'm not 100% sure about
 - [x] Write some reference story and character information
 - [x] Prepare an example spreadsheet and build in a translator pack for our translators
 - [x] Figure out an approximate wordcount
 - [x] Choose a translator, and contact them to see if they're available for the translation
 - [x] Implement the translation, playtest for issues
 - [x] Iterate on the translation as needed, find and address problems
 - [x] Once things are looking good, reach out to the rest of the Dicey Dungeons translators

Update!
 - [x] Esperanto
 - [x] Dutch
 - [x] Catalan
 - [x] German
 - [x] Italian
 - [x] Spanish
 - [x] Brazilian Portugese
 - [x] Russian
 - [x] Portugese
 - [x] Turkish
 - [x] French
 - [x] Irish
 - [x] Welsh
 - [x] Ukrainian
 - [x] Korean
 - [x] Simplified Chinese
 - [x] Traditional Chinese
 - [x] Japanese
 - [x] Polish
 - [x] Silesian

Update! We're into the final stretch now. Making a new to-do list:

 - [x] Make a final call on https://github.com/TerryCavanagh/VVVVVV/issues/860
 - [x] Make a final call on https://github.com/TerryCavanagh/VVVVVV/issues/904
 - [x] Get the sprites localised (https://github.com/TerryCavanagh/VVVVVV/issues/860)
 - [x] Finalise and confirm localisation credits in game https://github.com/TerryCavanagh/VVVVVV/issues/936
 - [x] Do an open beta for the translations on steam, tell people about it on Mastodon & *sigh* X
 - [x] Capture screenshots for all the steam supported languages (everything except IE, CY, SZ and CA I think)
 - [x] Make special Silesian screenshots for the Polish store page
 - [x] Update store text for 2023
 - [x] Write an announcement post for Steam
 - [x] Reach out to translators about translating missing strings and store text
 - [x] ...and also missing achievement strings
 - [x] Set up achievement translations on steam
 - [x] Set everything up on steam for the update
 - [x] Mention level editor on Steam store page

To do for release:
 - [x] Set the update live
 - [x] Blog posts, etc
 - [x] Let the translators know that the update is live

This should bring us to 100% on localisation!

**Comment by Fussmatte** [comment]
This question might be a bit off-base, but which languages do you plan to include in 2.4 that were in DD (besides CJK/Arabic)? I'm asking purely out of curiosity, since some of my friends might enjoy checking the game out in their native languages.

**Comment by TerryCavanagh** [comment]
My plan is to start with EFIGS, and see after that!

**Comment by TerryCavanagh** [comment]
Just a quick check in for anyone reading/wondering, I'm still chipping away at this to-do list, but slowly! (My focus at the minute is Dicey Dungeons DLC and mobile releases, which is happening pretty soon and monopolising my time right now.)

**Comment by Fussmatte** [comment]
How are things going with the checklist? Since the Dicey DLC has been out for a bit, I'm hoping there's time to go over some things here now...

**Comment by TerryCavanagh** [comment]
Yeah, sorry, this has been on the backburner for a while now, and might be for a bit longer yet (there are a couple final deadlines for upcoming Dicey related things that are keeping me busy, and then I need to shift focus to Super Hexagon related work for a bit). I haven't forgotten, just been busy!

**Comment by TerryCavanagh** [comment]
Progress: I've filled out the roomname notes for the `roomnames.xml` and `roomnames_special.xml`. Attached here for simplicity:

[roomnames_with_context.zip](https://github.com/TerryCavanagh/VVVVVV/files/9982830/roomnames_with_context.zip)

There are a couple of small things I want to check with Bennett, nothing too major. When he's had a look I'll continue with the next steps here.

Also: I've uploaded a zip file with a screenshot of each name room in the game, as an extra resource for translators. Downloadable here: https://thelettervsixtim.es/translatorassets/VVVVVV_rooms.zip

**Comment by Dav999-v** [comment]
Thanks, these explanations make everything much clearer! I never knew about the thing going on in the Final Level - I knew there were some references to television here and there, but I never realized how far it went, nor did I notice the contrast between black/white and color television.

Here's some questions/additions I have:

**I'm Sorry (1,0)** - Since the Purest Unobtainium trinket is so hidden, I think many translators will miss it in their first playthrough, so it might be good to notify them via the room name explanations that there's a path to a trinket (and thus more roomnames). After going through all the levels in roomname translator mode, it'll be obvious two rooms are missing, and the translator can then look at the screenshots, but maybe it helps for context and possible inspiration, if they know the passage is there?

**Hitting the Apex (4,18)** - This seems like it's about racing/motorsports to me, it's when a driver takes a curve on a racetrack in a certain ideal line, or something like that; and the room does have the player go around a curve. (There's also a film with this name apparently, but it came out in 2015)

**Indirect Jump Vector (5,17)** - Wait, how else would that jump be possible?

https://user-images.githubusercontent.com/44736680/201209982-239b9fa9-2a41-47a1-b1f5-e83bd80dbaa3.mp4

**Exhausted? (7,17)** - Not a question about the explanation, but I just realized that this was corrected from "Exausted?" in 2.3, and seeing that some other roomnames are wordplays, I'm starting to wonder if that misspelling could've been intended somehow?

**Television Newsveel (special)** - This is a play on Television Newsreel, but this wasn't immediately obvious.

Also, the localization readme (https://github.com/Dav999-v/VVVVVV/blob/localization/desktop_version/lang/README.txt) contains this unfinished section:

> === S T O R Y &nbsp; A N D &nbsp; C H A R A C T E R &nbsp; I N F O R M A T I O N ===
> 
> TODO: basic story information, crewmate names, ranks (Captain/Doctor/Professor/Officer/Chief), colors (and pink=purple in scripts), genders/pronouns (what if you're forced to specify Viridian's gender in another language), personalities, level of (in)formality between crewmates, relationships, the ship and why it's called "D.S.S. Souleye", who wrote these "personal logs" you can find on terminals...

Could you write something for this as well? I had an idea of what things would be relevant for translators to know, but you could probably explain all this better than me.

**Comment by InfoTeddy** [comment]
**Easy Mode Unlocked (18,10)** - This refers to the second passageway on the right side that is easier to take when going back through this room on the way down, but that passageway leads to death.

**I Can't Believe You Got This Far** and **Imagine Spikes There, if You Like (11,7)** - Both of these room names accompany the same altered room, with spikes removed so as to make collecting the trinket possible without dying.

**Comment by TerryCavanagh** [comment]
Thank you for the notes!

I actually heard back from Bennett much sooner than expected, so I've updated the notes with his details, and the changes in your posts @Dav999-v and @InfoTeddy:

[roomnames_with_context_v2.zip](https://github.com/TerryCavanagh/VVVVVV/files/9991354/roomnames_with_context_v2.zip)

> Also, the localization readme (https://github.com/Dav999-v/VVVVVV/blob/localization/desktop_version/lang/README.txt) contains this unfinished section:
> 
> > === S T O R Y   A N D   C H A R A C T E R   I N F O R M A T I O N ===
> > TODO: basic story information, crewmate names, ranks (Captain/Doctor/Professor/Officer/Chief), colors (and pink=purple in scripts), genders/pronouns (what if you're forced to specify Viridian's gender in another language), personalities, level of (in)formality between crewmates, relationships, the ship and why it's called "D.S.S. Souleye", who wrote these "personal logs" you can find on terminals...
> 
> Could you write something for this as well? I had an idea of what things would be relevant for translators to know, but you could probably explain all this better than me.

Cool, no problem! I'll add this to my task list, and have a look soon!

**Comment by Dav999-v** [comment]
Perfect, thanks! I'll add it to the readme.

**Comment by TerryCavanagh** [comment]
I've reached out to one of my translators to get thier opinions and feedback on all this! I'll report back!

(Estimated wordcount looks to be just short of 8,000 words, by the way!)

**Comment by Dav999-v** [comment]
Thanks for the update! 👍🏼 

Also a small update from me - I've just added one more localization feature this weekend: a menu option for translators to explore any level in the main game. The original thought was that to translate the room names, translators would always play the full game and then use the time trials to revisit levels as needed (all optionally in invincibility). But the time trials cause just a bit too many problems (especially when you can't translate the last room) so I added this dedicated mode to make the experience as smooth as possible.

![Explore game menu](https://user-images.githubusercontent.com/44736680/204615416-f8f6895e-2975-4d3b-9f26-fdb3737177be.png)

**Comment by TerryCavanagh** [comment]
Ohhh, that's really good! Nice going!

(The translator pack I sent out today was up to date with the latest commit, so that's been included!)

**Comment by TerryCavanagh** [comment]
We're in the final stretch now! Updated the first post with an expanded to-do list.

**Comment by TerryCavanagh** [comment]
Done!
